language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-gflux' ]; then cd .. && eval "mv $currentfolder generator-gflux" && cd generator-gflux; fi
